version = 1
identifier = "default"
description = "Capacités nécessaires pour Loop Visualizer"
windows = ["main"]
webviews = ["main"]
remote = { urls = ["http://localhost:1420/*"] }
permissions = [
  "core:default",
  "dialog:default",
  "dialog:allow-open",
  "dialog:allow-save",
  "dialog:allow-message",
  "dialog:allow-ask",
  "dialog:allow-confirm",
  "shell:default",
  "shell:allow-open",
  "shell:allow-spawn",
  "shell:allow-kill",
  "shell:allow-stdin-write",
  { identifier = "shell:allow-execute", allow = [ { name = "ffmpeg", sidecar = true, args = true } ] }
]
